-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS total_amount
FROM cleaned_data
GROUP BY gender
ORDER BY total_amount DESC;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2) AS avg_rating
FROM cleaned_data
GROUP BY item_purchased
HAVING AVG(review_rating) > (
    SELECT AVG(review_rating) 
    FROM cleaned_data
)
ORDER BY avg_rating DESC
LIMIT 5;

-- Q4. Compare the average purchase amounts between Standard and Express shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM cleaned_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       SUM(purchase_amount) AS total_revenue
FROM cleaned_data
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(
         (COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*)), 2
       ) AS discount_percentage
FROM cleaned_data
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;
-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT 
    CASE 
        WHEN previous_purchases BETWEEN 0 AND 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 8 THEN 'Returning'
        WHEN previous_purchases > 10 THEN 'Loyal'
    END AS customer_segment,
    COUNT(DISTINCT customer_id) AS customer_count
FROM cleaned_data
GROUP BY customer_segment
ORDER BY customer_count DESC;
-- Q8. What are the top 3 most purchased products within each category?
SELECT category, item_purchased, purchase_count
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rank_in_category
    FROM cleaned_data
    GROUP BY category, item_purchased
) ranked
WHERE rank_in_category <= 3
ORDER BY category, purchase_count DESC;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS buyer_type,
    subscription_status,
    COUNT(DISTINCT customer_id) AS customer_count
FROM cleaned_data
GROUP BY buyer_type, subscription_status
ORDER BY buyer_type, subscription_status;
-- Q10. What is the revenue contribution of each age group?
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue,
    ROUND(
        SUM(purchase_amount) * 100.0 / (SELECT SUM(purchase_amount) FROM cleaned_data), 
        2
    ) AS revenue_percentage
FROM cleaned_data
GROUP BY age_group
ORDER BY total_revenue DESC;